name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - beta
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "docs/*"
  pull_request:
    branches:
      - master
      - beta
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "docs/*"
  release:
    types: [published]

jobs:
  sample-job-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create sample binary archive
        shell: bash
        run: |
          tar -czvf sample-zip.tar.gz *

      - uses: actions/upload-artifact@v4
        with:
          name: sample-zip
          path: sample-zip.tar.gz
          if-no-files-found: error

  sample-job-msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: actions/upload-artifact@v4
        with:
          name: sample-zip-msvc
          path: ${{ github.workspace }}/*
          if-no-files-found: error

  create-latest:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [sample-job-linux, sample-job-msvc]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create binary archives
        run: |
          7z a -r sample-zip-windows.zip ./sample-zip-msvc/*
          mv ./sample-zip/* ./sample-zip.tar.gz

      - name: Create latest build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_RELEASE_COMMIT=$(gh api repos/${{ github.repository }}/releases/tags/latest --jq '.target_commitish' 2>/dev/null || echo "")
          gh release delete latest --cleanup-tag --yes || true
          
          RELEASE_BODY="## Commits"
          
          if [ -n "$LATEST_RELEASE_COMMIT" ]; then
            COMMITS=$(git log $LATEST_RELEASE_COMMIT..HEAD --pretty=format:"%h|%s|%an")
          else
            COMMITS=$(git log -3 --pretty=format:"%h|%s|%an")
          fi
          
          while IFS='|' read -r hash subject author; do
            if [[ $subject =~ ^Merge\ pull\ request\ \#([0-9]+) ]]; then
              PR_NUM="${BASH_REMATCH[1]}"
              if [[ $subject =~ from.*\/(.*)$ ]]; then
                BRANCH_NAME="${BASH_REMATCH[1]}"
                RELEASE_BODY+=$'\n'"- $hash: Merge pull request #${PR_NUM} from ${BRANCH_NAME} ($author)"
              else
                RELEASE_BODY+=$'\n'"- $hash: $subject ($author)"
              fi
            else
              if [[ $subject =~ \(#([0-9]+)\)$ ]]; then
                PR_NUM="${BASH_REMATCH[1]}"
                subject=$(echo "$subject" | sed 's/ (#[0-9]\+)$//')
                PR_LINK=" [#${PR_NUM}](https://github.com/${{ github.repository }}/pull/${PR_NUM})"
                RELEASE_BODY+=$'\n'"- $hash: $subject ($author)${PR_LINK}"
              else
                RELEASE_BODY+=$'\n'"- $hash: $subject ($author)"
              fi
            fi
          done <<< "$COMMITS"
          
          # Create release
          gh release create latest \
            --title "Latest Build" \
            --notes "$RELEASE_BODY" \
            --target ${{ github.sha }} \
            sample-zip.tar.gz

  create-prerelease:
    if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
    needs: [sample-job-linux, sample-job-msvc]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create binary archives
        run: |
          mv ./sample-zip/* ./sample-zip.tar.gz
          7z a -r sample-zip-windows.zip ./sample-zip-msvc/*

      - name: Create latest beta build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_BETA_COMMIT=$(gh api repos/${{ github.repository }}/releases/tags/latest-beta --jq '.target_commitish' 2>/dev/null || echo "")
          gh release delete latest-beta --cleanup-tag --yes || true
          
          RELEASE_BODY="## Commits"
          
          if [ -n "$LATEST_BETA_COMMIT" ]; then
            COMMITS=$(git log $LATEST_BETA_COMMIT..HEAD --pretty=format:"%h|%s|%an")
          else
            COMMITS=$(git log -3 --pretty=format:"%h|%s|%an")
          fi
          
          while IFS='|' read -r hash subject author; do
            if [[ $subject =~ ^Merge\ pull\ request\ \#([0-9]+) ]]; then
              PR_NUM="${BASH_REMATCH[1]}"
              if [[ $subject =~ from.*\/(.*)$ ]]; then
                BRANCH_NAME="${BASH_REMATCH[1]}"
                RELEASE_BODY+=$'\n'"- $hash: Merge pull request #${PR_NUM} from ${BRANCH_NAME} ($author)"
              else
                RELEASE_BODY+=$'\n'"- $hash: $subject ($author)"
              fi
            else
              if [[ $subject =~ \(#([0-9]+)\)$ ]]; then
                PR_NUM="${BASH_REMATCH[1]}"
                subject=$(echo "$subject" | sed 's/ (#[0-9]\+)$//')
                PR_LINK=" [#${PR_NUM}](https://github.com/${{ github.repository }}/pull/${PR_NUM})"
                RELEASE_BODY+=$'\n'"- $hash: $subject ($author)${PR_LINK}"
              else
                RELEASE_BODY+=$'\n'"- $hash: $subject ($author)"
              fi
            fi
          done <<< "$COMMITS"
          
          # Create release
          gh release create latest-beta \
            --title "Beta Build" \
            --notes "$RELEASE_BODY" \
            --target ${{ github.sha }} \
            --prerelease \
            sample-zip.tar.gz

  create-release:
    if: github.event_name == 'release'
    needs: [sample-job-linux, sample-job-msvc]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - artifact_dir: sample-zip
            artifact_name: sample-zip.tar.gz
            zip: false

          - artifact_dir: sample-zip-windows
            artifact_name: sample-zip-windows.zip
            zip: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create archive
        run: |
          if [ "${{ matrix.zip }}" == "true" ]; then
            7z a -r ${{ matrix.artifact_name }} ./${{ matrix.artifact_dir }}/*
          else
            mv ./${{ matrix.artifact_dir }}/* ${{ matrix.artifact_name }}
          fi

      - name: Upload archives to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
            "${{ matrix.artifact_name }}" \
            --clobber